language: node_js
node_js:
    - 12

services:
    - docker

before_install:
    - docker network create test-network
    - docker build -t dedsecknight/backend-test -f Dockerfile.dev .

before_script:
    - docker run --name db --net test-network -e MYSQL_ROOT_PASSWORD=abc12345 -e MYSQL_DATABASE=quiz-backend-test -d mysql --default-authentication-plugin=mysql_native_password
    - sleep 30

script:
    - docker run --name backend-test --restart on-failure --net test-network -e CI=true dedsecknight/backend-test npm run test

after_script:
    - docker stop db
    - docker rm db
    - docker rm backend-test
    - docker network rm test-network
